USE [master]
GO

/****** Object:  Database [ApacheLogs]    Script Date: 11/20/2010 16:06:07 ******/
CREATE DATABASE [ApacheLogs] ON  PRIMARY 
( NAME = N'ApacheLogs', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\ApacheLogs.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ApacheLogs_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\ApacheLogs_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ApacheLogs] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ApacheLogs].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ApacheLogs] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ApacheLogs] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ApacheLogs] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ApacheLogs] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ApacheLogs] SET ARITHABORT OFF 
GO

ALTER DATABASE [ApacheLogs] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ApacheLogs] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ApacheLogs] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ApacheLogs] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ApacheLogs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ApacheLogs] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ApacheLogs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ApacheLogs] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ApacheLogs] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ApacheLogs] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ApacheLogs] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ApacheLogs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ApacheLogs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ApacheLogs] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ApacheLogs] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ApacheLogs] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ApacheLogs] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ApacheLogs] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ApacheLogs] SET  READ_WRITE 
GO

ALTER DATABASE [ApacheLogs] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ApacheLogs] SET  MULTI_USER 
GO

ALTER DATABASE [ApacheLogs] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ApacheLogs] SET DB_CHAINING OFF 
GO


